#ifndef SYSCALL_HEADER
#define SYSCALL_HEADER

#include <dlfcn.h>
#include <stdio.h>
#include <string.h>

#include <cstdlib>
#include <iostream>
#include <thread>

#define DEBUG_THREAD_DEFAULT_ENABLE true
#define DEBUG_PRINT_WHEN_EXIT true
#define DEBUG_LEVEL 2

#define DEBUG_MSG(level, str)      \
  if (level <= DEBUG_LEVEL) {      \
    std::cout << str << std::endl; \
  }

void native_init_syscalls();
const char *syscall_enum_to_name(int index);

// index
namespace SysCallIndex {
enum {
  real_syscall = 0,
  real_puts,
  real_read,
  real_write,
  real_open,
  real_close,
  real_stat,
  real_fstat,
  real_lstat,
  real_poll,
  real_lseek,
  real_mmap,
  real_mprotect,
  real_munmap,
  real_brk,
  real_sbrk,
  real_ioctl,
  real_pread,
  real_pwrite,
  real_readv,
  real_writev,
  real_access,
  real_pipe,
  real_select,
  real_sched_yield,
  real_mremap,
  real_msync,
  real_mincore,
  real_madvise,
  real_shmget,
  real_shmat,
  real_shmctl,
  real_dup,
  real_dup2,
  real_pause,
  real_nanosleep,
  real_getitimer,
  real_alarm,
  real_setitimer,
  real_getpid,
  real_sendfile,
  real_socket,
  real_connect,
  real_accept,
  real_sendto,
  real_recvfrom,
  real_sendmsg,
  real_recvmsg,
  real_shutdown,
  real_bind,
  real_listen,
  real_getsockname,
  real_getpeername,
  real_socketpair,
  real_setsockopt,
  real_getsockopt,
  real_clone,
  real_fork,
  real_vfork,
  real_execve,
  real_wait4,
  real_kill,
  real_uname,
  real_semget,
  real_semop,
  real_semctl,
  real_shmdt,
  real_msgget,
  real_msgsnd,
  real_msgrcv,
  real_msgctl,
  real_fcntl,
  real_flock,
  real_fsync,
  real_fdatasync,
  real_truncate,
  real_ftruncate,
  real_getdents64,
  real_getcwd,
  real_chdir,
  real_fchdir,
  real_rename,
  real_mkdir,
  real_rmdir,
  real_creat,
  real_link,
  real_unlink,
  real_symlink,
  real_readlink,
  real_chmod,
  real_fchown,
  real_chown,
  real_lchown,
  real_umask,
  real_gettimeofday,
  real_getrlimit,
  real_getrusage,
  real_sysinfo,
  real_times,
  real_ptrace,
  real_getuid,
  real_syslog,
  real_vsyslog,
  real_getgid,
  real_setuid,
  real_setgid,
  real_geteuid,
  real_getegid,
  real_setpgid,
  real_getpgid,
  real_getpgrp,
  real_setsid,
  real_setreuid,
  real_setregid,
  real_getgroups,
  real_setgroups,
  real_setresuid,
  real_setresgid,
  real_getresuid,
  real_getresgid,
  real_setfsuid,
  real_setfsgid,
  real_getsid,
  real_sigaltstack,
  real_utime,
  real_mknod,
  real_uselib,
  real_personality,
  real_ustat,
  real_statfs,
  real_fstatfs,
  real_sysfs,
  real_getpriority,
  real_setpriority,
  real_sched_setparam,
  real_sched_getparam,
  real_sched_setscheduler,
  real_sched_getscheduler,
  real_sched_get_priority_max,
  real_sched_get_priority_min,
  real_sched_rr_get_interval,
  real_mlock,
  real_munlock,
  real_mlockall,
  real_munlockall,
  real_vhangup,
  real_sysctl,
  real_prctl,
  real_adjtimex,
  real_setrlimit,
  real_chroot,
  real_sync,
  real_acct,
  real_settimeofday,
  real_mount,
  real_umount2,
  real_swapon,
  real_swapoff,
  real_reboot,
  real_sethostname,
  real_setdomainname,
  real_iopl,
  real_ioperm,
  real_quotactl,
  real_gettid,
  real_readahead,
  real_setxattr,
  real_lsetxattr,
  real_fsetxattr,
  real_getxattr,
  real_lgetxattr,
  real_fgetxattr,
  real_listxattr,
  real_llistxattr,
  real_flistxattr,
  real_removexattr,
  real_lremovexattr,
  real_fremovexattr,
  real_time,
  real_sched_setaffinity,
  real_sched_getaffinity,
  real_epoll_create,
  real_remap_file_pages,
  real_semtimedop,
  real_posix_fadvise,
  real_timer_create,
  real_timer_settime,
  real_timer_gettime,
  real_timer_getoverrun,
  real_timer_delete,
  real_clock_gettime,
  real_clock_settime,
  real_clock_getres,
  real_clock_nanosleep,
  real_epoll_wait,
  real_epoll_ctl,
  real_tgkill,
  real_utimes,
  real_set_mempolicy,
  real_mq_open,
  real_mq_unlink,
  real_mq_timedsend,
  real_mq_timedreceive,
  real_mq_notify,
  real_waitid,
  real_inotify_init,
  real_inotify_add_watch,
  real_inotify_rm_watch,
  real_openat,
  real_mkdirat,
  real_mknodat,
  real_fchownat,
  real_futimesat,
  real_fstatat,
  real_unlinkat,
  real_renameat,
  real_linkat,
  real_symlinkat,
  real_readlinkat,
  real_fchmodat,
  real_faccessat,
  real_pselect,
  real_ppoll,
  real_unshare,
  real_splice,
  real_tee,
  real_sync_file_range,
  real_vmsplice,
  real_utimensat,
  real_epoll_pwait,
  real_signalfd,
  real_timerfd_create,
  real_eventfd,
  real_fallocate,
  real_timerfd_settime,
  real_timerfd_gettime,
  real_accept4,
  real_epoll_create1,
  real_dup3,
  real_pipe2,
  real_inotify_init1,
  real_preadv,
  real_pwritev,
  real_recvmmsg,
  real_fanotify_init,
  real_fanotify_mark,
  real_prlimit,
  real_name_to_handle_at,
  real_open_by_handle_at,
  real_clock_adjtime,
  real_syncfs,
  real_sendmmsg,
  real_setns,
  real_getcpu,
  real_process_vm_readv,
  real_process_vm_writev,
  real_renameat2,
  real_getrandom,
  real_memfd_create,
  real_bpf,
  real_execveat,
  real_mlock2,
  real_copy_file_range,
  real_preadv2,
  real_pwritev2,
  real_pkey_mprotect,
  real_pkey_alloc,
  real_pkey_free,
  real_statx,
  MAX_NUM,
};

const char *name(int index);

}

#endif
